general features ready
pochtalexa/go-cti-middleware-dev pull request #1
Opened 2023-11-21 10:17 UTC by pochtalexa

2023-11-21 15:40 UTC, gonozov0 requested changes
Отличное начало 👍

Из критичных моментов, с которыми нужно будет разобраться и реализовать:

1. Где-то спавнишь горутины, но никак не обрабатываешь в них возможные ошибки, а они скорее всего должны влиять на работу в основном потоке. Также нет обработки, что если ошибка в основном потоке, то все горутины должны быть отменены, иначе это может приводить к утечке памяти.
Правильный подход - это создавать отдельный канал для ошибок, создавать контекст с возможностью отмены и передавать это все в горутины с обработкой отмены контекста и чтения из канала ошибок в основном потоке.

2. Нету интерфейсов и интеграционных тестов.
Для всех клиентов, который ходят во внешний мир, в том числе и базе данных, должны быть определены интерфейсы и InMemory/Mock реализация для них. Они важны для интеграционных тестов api сервера, чтобы в них была протестирована вся бизнес логика и при этом не было походов во внешний мир.

2023-11-21 15:40 UTC, gonozov0 commented on cmd/agentcti/main.go
> +	go pgui.Init()
Что будет, если тут произойдет ошибка в горутине? Нам не нужно прерывать основной поток выполнения?

2023-11-21 15:40 UTC, gonozov0 commented on cmd/agentcti/main.go
> +	}
Выглядит, как бизнес логика, ее не должно быть в main, нужно переносить в internal

2023-11-21 15:40 UTC, gonozov0 commented on cmd/agentcti/main.go
> +		//log.Info().Str("resp[state]", fmt.Sprintln(resp["state"])).Msg("")
Ненужные комментарии необходимо сразу удалять

2023-11-21 15:40 UTC, gonozov0 commented on cmd/servercti/main.go
> +	}
Выглядит также, как бизнес логика

2023-11-21 15:40 UTC, gonozov0 commented on cmd/servercti/main.go
> +	go ws.ReadMessage(wsConn, storage.AgentsInfo)
Аналогично, что будет, если тут произойдет паника в горутине, не должно ли это повлиять на логику выполнения в основном потоке?

2023-11-21 15:40 UTC, gonozov0 commented on internal/agent/logger/logger.go
> +	//log.Logger = log.Output(writers)
.

2023-11-21 15:40 UTC, gonozov0 commented on internal/server/api/api.go
> +	//})
Почему закомментировал? Старайся не сохранять лишний код в комментариях, это плохая привычка, любой старый код можно вернуть через git

2023-11-21 15:40 UTC, gonozov0 commented on internal/server/storage/storage.go
Для всего, что ходит в базу данных или во внешний мир, должен быть определен интерфейс, и в бизнес логике использован именно интерфейс. Здесь много кода, но интерфейса не увидел
Также нам будет нужен InMemoryStorage, чтобы запускать интеграционный тесты на хендлеры, в которых не будет реальных запросов в бд или внешний мир.

2024-01-14 22:36 UTC, avhitrov requested changes
Первые комментарии к рассмотрению и исправлению.

2024-01-14 22:36 UTC, avhitrov commented on cmd/agentcti/main.go
> +	}
https://pkg.go.dev/time#Tick
По выходу из цикла, тикер останется в памяти, продолжит тикать и будет "течь", так как сборщик мусора не сможет его освободить. Разумнее создать переменную-тикер с помощью NewTicker, и после выхода из цикла освободить его через ticker.Stop()

Кроме того, имеет смысл сделать ограничение по количеству попыток неуспешной авторизации. При достижении этого количества падать по Fatal, чтобы не флудить сервер.

2024-01-14 22:36 UTC, avhitrov commented on internal/agent/pgui/pgui.go
> +	checkStatusCode(res.StatusCode, op)
Этот блок одинаков для всех функций модуля, его вполне можно выделить в отдельную локальную для модуля функцию.

2024-01-14 22:36 UTC, avhitrov commented on internal/agent/storage/config.go
> +}
Обращение к структуре из более чем одной горутин без блокировки рано или поздно приведет к DATA RACE condition. В частности, при переполучении Токена авторизации. Одновременное чтение его из оконной горутины и перезапись из main приведет к тому, что обращение к мидлваре будет произведено по старому токену и приведет к ошибке авторизации. Следует нагрузить данную структуру мьютексом и все запросы на изменение чувствительных полей, которые могут быть сделаны через конкурентные вызовы, осуществлять через функции данной структуры (SetToken / GetToken), которые будут включать и выключать мьютекс при чтении-записи поля.

2024-01-14 22:36 UTC, avhitrov commented on cmd/agentcti/main.go
> +		}
Если данный проект является чем-то, что должно работать в реальной жизни, а не только в качестве сферического коня в вакууме, необходимо предусмотреть переопрос эндпоинта в случае получения невалидного JSON. Иначе один битый сетевой пакет или кратковременная потеря соединения будет приводить к падению приложения. При работе с сетью, особенно если авторизующее приложение находится на некотором удалении от клиента принято делать три попытки.

2024-01-14 22:36 UTC, avhitrov commented on internal/agent/auth/auth.go
> +	storage.AppConfig.TokenString = tokenString.Token
Потенциальное место для возникновения гонок.

2024-01-14 22:36 UTC, avhitrov commented on internal/agent/logger/logger.go
> +	//log.Logger = log.Output(writers)
Не знаю, что имел в виду предыдущий ревьюер, скорее всего, то, что не следует оставлять закомментированный код, особенно при использовании системы версионирования.

2024-01-14 22:36 UTC, avhitrov commented on internal/agent/pgui/pgui.go
> +	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", storage.AppConfig.TokenString))
```suggestion
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", storage.AppConfig.GetTokenString()))
```

2024-01-14 22:36 UTC, avhitrov commented on cmd/servercti/main.go
> +	"github.com/rs/zerolog/log"
https://t.me/bushigo/27

2024-01-14 22:36 UTC, avhitrov commented on internal/server/api/api.go
> +	//})
👍

2024-01-14 22:36 UTC, avhitrov commented on internal/server/config/config.go
> +	c.Secret = "your-256-bit-secret"
Поставлю здесь галочку для обсуждения, так как передача секрета в приложение в любой production системе может осуществляться только извне.

2024-01-14 22:36 UTC, avhitrov commented on internal/server/migrations/01_init.sql
> +-- +goose Down
Если уж заведена секция отката, необходимо прописать в ней код отката. Что-то вроде
```
DROP TABLE IF EXISTS users;
```

2024-01-24 22:14 UTC, avhitrov approved these changes
Мелкие придирки: я неверно объяснил форматирование импортов, и в одном месте замечен лишний defer. В остальном - аппрув, далее пол логике требуется все это выкатить куда-нибудь на стенд и хорошо потестировать.

2024-01-24 22:14 UTC, avhitrov commented on cmd/agentcti/main.go
> +)
Нет! Видимо, я был не очень очевиден, когда писал пост в телеграме. Блок - это список импортов, отделенный от остальных двойным переносом строк.
```suggestion
import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/gdamore/tcell/v2"
	"github.com/rs/zerolog/log"
	"github.com/sethvargo/go-retry"

	"github.com/pochtalexa/go-cti-middleware/internal/agent/auth"
	"github.com/pochtalexa/go-cti-middleware/internal/agent/flags"
	"github.com/pochtalexa/go-cti-middleware/internal/agent/logger"
	"github.com/pochtalexa/go-cti-middleware/internal/agent/pgui"
	"github.com/pochtalexa/go-cti-middleware/internal/agent/storage"
)
```
Как-то так. В принципе, это не блокер, просто хотел внести ясность.

2024-01-24 22:14 UTC, avhitrov commented on cmd/agentcti/main.go
> +	defer tickerAuth.Stop()
Вот этот defer становится не нужен. Если приложение падает по Fatal, все defer-ы все равно прервутся. А если цикл завершится штатно, то после него уже выставлен явный Stop().

2024-03-13 16:48 UTC, merged